function comparePlotsUsingdiffSetting(figFolder, saveFolder, varargin)
    % Compare plots generated by the same process using different settings.
    % Figures with the same name in 'folder1' and 'folder2' will be combined into a new figure and
    % saved in saveFolder using the same name. Only figures containing a specified 'keyword' in their
    % filename will be combined if the 'keyword' parameter is provided, and files containing an
    % 'ignoreKeyword' in their filename will be excluded.

    % Inputs:
        % figFolder (required): Path to the folder where the original figures are stored.
        % saveFolder (required): Path to the folder where the combined figures will be saved.
        % label1 (optional): Label for the figures from folder1. Defaults to 'fig1'.
        % label2 (optional): Label for the figures from folder2. Defaults to 'fig2'.
        % figExt (optional): File extension for the figure files. Defaults to 'jpg'.
        % keyword (optional): Keyword to filter the figures to be combined. Only figures containing this keyword in their name will be combined.
        % ignoreKeyword (optional): Keyword to ignore figures. Figures containing this keyword in their name will be excluded from combining.

    % Outputs:
        % None (the function saves the combined figure files directly in the specified saveFolder).

    % Create an input parser object
    parser = inputParser;

    % Define the required inputs
    addRequired(parser, 'figFolder', @ischar);  % Folder to load original figures
    addRequired(parser, 'saveFolder', @ischar); % Folder to save combined figures

    % Define the optional inputs
    addParameter(parser, 'label1', 'fig1', @(x) ischar(x) || isstring(x));  % Label for folder1 figures
    addParameter(parser, 'label2', 'fig2', @(x) ischar(x) || isstring(x));  % Label for folder2 figures
    addParameter(parser, 'figExt', 'jpg', @ischar);                         % Figure file extension
    addParameter(parser, 'keyword', '', @ischar);                           % Keyword to filter figures by name
    addParameter(parser, 'ignoreKeyword', '', @ischar);                     % Keyword to ignore figures by name

    % Parse the inputs
    parse(parser, figFolder, saveFolder, varargin{:});

    % Convert the labels to char arrays to avoid inputParser issues
    label1 = char(parser.Results.label1);
    label2 = char(parser.Results.label2);
    figExt = char(parser.Results.figExt);
    keyword = char(parser.Results.keyword);
    ignoreKeyword = char(parser.Results.ignoreKeyword);

    % Get the parsed inputs
    figFolder = parser.Results.figFolder;
    saveFolder = parser.Results.saveFolder;

    % Open a GUI to choose folder1 and get the list of figure files with the extension specified by 'figExt'
    folder1 = uigetdir(figFolder, 'Select Folder 1');
    if folder1 == 0
        error('No folder selected for Folder 1.');
    end

    % Handle empty keyword separately
    if isempty(keyword)
        searchPattern1 = fullfile(folder1, ['*.' figExt]);
    else
        searchPattern1 = fullfile(folder1, ['*' keyword '*.' figExt]);
    end

    % Get the list of files
    files1 = dir(searchPattern1);

    % Open a GUI to choose folder2 and get the list of figure files with the extension specified by 'figExt'
    folder2 = uigetdir(figFolder, 'Select Folder 2');
    if folder2 == 0
        error('No folder selected for Folder 2.');
    end

    % Handle empty keyword separately
    if isempty(keyword)
        searchPattern2 = fullfile(folder2, ['*.' figExt]);
    else
        searchPattern2 = fullfile(folder2, ['*' keyword '*.' figExt]);
    end

    % Get the list of files
    files2 = dir(searchPattern2);

    % Open a GUI to choose a folder to save the combined figure. Use savePath as a default
    saveFolder = uigetdir(saveFolder, 'Select a folder to save combined figures');
    if saveFolder == 0
        error('No folder selected for saving.');
    end

    % Loop through the folder1 figure list. For every folder1 figure, look for the figure with the
    % same name in folder2. Combine them in a new figure
    for n = 1:length(files1)
        [~, figName1, ext1] = fileparts(files1(n).name);

        % Skip files that contain the ignoreKeyword
        if ~isempty(ignoreKeyword) && contains(figName1, ignoreKeyword)
            continue;
        end

        % Check if the figure with the same name exists in folder2
        fig2File = fullfile(folder2, [figName1, '.', figExt]);
        if exist(fig2File, 'file')
            % Get the fig1 from folder1
            fig1File = fullfile(folder1, files1(n).name);

            % Get the fig2 from folder2
            fig2File = fullfile(folder2, [figName1, '.', figExt]);

            % Create a savePath
            savePath = fullfile(saveFolder, [figName1, '.', figExt]); % Use the original fig name

            % Combine fig1 and fig2. Label them and save the combined fig
            combineImages(fig1File, fig2File, 'savePath', savePath, 'label1', label1, 'label2', label2);
        end
    end
end
