function compareLatexTablesUsingDiffSetting(tableFolder, saveFolder, varargin)
    % Compare LaTeX files generated by the same process using different settings.
    % Files with the same name in 'folder1' and 'folder2' will be combined into a new file and
    % saved in saveFolder using the same name. Only files containing a specified 'keyword' in their
    % filename will be combined if the 'keyword' parameter is provided, and files containing an
    % 'ignoreKeyword' in their filename will be excluded.

    % Inputs:
        % tableFolder (required): Path to the folder where the original files are stored.
        % saveFolder (required): Path to the folder where the combined files will be saved.
        % label1 (optional): Label (LaTeX comment) for the files from folder1. Defaults to 'Table 1'.
        % label2 (optional): Label (LaTeX comment) for the files from folder2. Defaults to 'Table 2'.
        % tableExt (optional): File extension for the LaTeX files. Defaults to 'tex'.
        % keyword (optional): Keyword to filter the files to be combined. Only files containing this keyword in their name will be combined.
        % ignoreKeyword (optional): Keyword to ignore files. Files containing this keyword in their name will be excluded from combining.

    % Outputs:
        % None (the function saves the combined LaTeX files directly in the specified saveFolder).

    % Create an input parser object
    parser = inputParser;
    
    % Define the required inputs
    addRequired(parser, 'tableFolder', @ischar); % Folder to load original LaTeX files
    addRequired(parser, 'saveFolder', @ischar);  % Folder to save combined LaTeX files
    
    % Define the optional inputs
    addParameter(parser, 'label1', 'Table 1', @(x) ischar(x) || isstring(x)); % Label for files from folder1
    addParameter(parser, 'label2', 'Table 2', @(x) ischar(x) || isstring(x)); % Label for files from folder2
    addParameter(parser, 'tableExt', 'tex', @ischar);   % File extension for LaTeX files
    addParameter(parser, 'keyword', '', @ischar);       % Keyword to filter the files by name
    addParameter(parser, 'ignoreKeyword', '', @ischar); % Keyword to ignore files by name
    
    % Parse the inputs
    parse(parser, tableFolder, saveFolder, varargin{:});
    
    % Get the parsed inputs
    tableFolder = parser.Results.tableFolder;
    saveFolder = parser.Results.saveFolder;
    label1 = parser.Results.label1;
    label2 = parser.Results.label2;
    tableExt = parser.Results.tableExt;
    keyword = parser.Results.keyword;
    ignoreKeyword = parser.Results.ignoreKeyword;

    % Open a GUI to choose folder1 and get the list of files with the extension specified by 'tableExt'
    folder1 = uigetdir(tableFolder, 'Select Folder 1');
    if folder1 == 0
        error('No folder selected for Folder 1.');
    end

    % Handle empty keyword separately
    if isempty(keyword)
        searchPattern1 = fullfile(folder1, ['*.' tableExt]);
    else
        searchPattern1 = fullfile(folder1, ['*' keyword '*.' tableExt]);
    end

    % Get the list of files
    files1 = dir(searchPattern1);
    
    % Open a GUI to choose folder2 and get the list of files with the extension specified by 'tableExt'
    folder2 = uigetdir(tableFolder, 'Select Folder 2');
    if folder2 == 0
        error('No folder selected for Folder 2.');
    end

    % Handle empty keyword separately
    if isempty(keyword)
        searchPattern2 = fullfile(folder2, ['*.' tableExt]);
    else
        searchPattern2 = fullfile(folder2, ['*' keyword '*.' tableExt]);
    end

    % Get the list of files
    files2 = dir(searchPattern2);
    
    % Open a GUI to choose a folder to save the combined files. Use saveFolder as a default
    saveFolder = uigetdir(saveFolder, 'Select a folder to save combined files');
    if saveFolder == 0
        error('No folder selected for saving.');
    end
    
    % Loop through the folder1 file list. For every file in folder1, look for the file with the
    % same name in folder2. Combine them in a new file
    for n = 1:length(files1)
        [~, fileName, ext1] = fileparts(files1(n).name);
        
        % Skip files that contain the ignoreKeyword
        if ~isempty(ignoreKeyword) && contains(fileName, ignoreKeyword)
            continue;
        end
        
        % Check if the file with the same name exists in folder2
        file2 = fullfile(folder2, [fileName, '.', tableExt]);
        if exist(file2, 'file')
            % Get the file1 from folder1
            file1 = fullfile(folder1, files1(n).name);

            % Get the file2 from folder2
            file2 = fullfile(folder2, [fileName, '.', tableExt]);

            % Create a savePath
            savePath = fullfile(saveFolder, [fileName, '.', tableExt]); % Use the original file name

            % Combine file1 and file2. Label them and save the combined file
            combineLatexFiles(file1, file2, 'savePath', savePath, 'label1', label1, 'label2', label2);
        end
    end
end
